import Header from "@/components/global/header/header";
import Sidebar from "@/components/global/sidebar/sidebar";

import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-6`}
      >
        <Header />
        <div className="grid grid-cols-3">
          <div className="col-span-1">
            <Sidebar />
          </div>
          <div className="col-span-2">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
